### ISSUE TITLE
msg.html_body is None

### ISSUE THREAD

**Issue by byy-git** [scanny/python-oxmsg#2]
1.When the code is used to read the msg mail, the field 'html_body' exists, but its corresponding value is None.
2.There is a table in the message, but the table structure cannot be restored from the text that was read from the field 'body' or another variable.

**Comment by scanny** [comment]
Please provide a minimum reproducible example with a file that exhibits this behavior and I'll take a look.

It could be the table is present in the RTF body but the message has no HTML body.

**Comment by byy-git** [comment]
when I debug this code:
>> from oxmsg import Message
>> file_path = "exanple.msg"
>> msg = Message.load(file_path)
>> body = msg.body
>> html_body = msg.html_body
the object "msg" has attribute named "body" and "html_body" . I tried to extract "html_body" with several files, but, its corresponding value is always None.
This makes me wonder, why is this attribute there if it's useless?

Thank you for your answer.

**Comment by scanny** [comment]
`Message.html_body` returns the messages as HTML when an HTML version is present in the message. When there is no HTML version it returns `None`.

So you can infer from your results that the MSG items you're looking at have no HTML "alternative" format.

It could be they have a rich text version in RTF form though, you could try this to find out:
```python
from oxmsg.domain import constants as c

compressed_rtf_bytes = msg.binary_prop_value(c.PID_RTF_COMPRESSED)
```

This will either return `None` or `bytes`. You'll have to look up how to expand the compressed RTF, I haven't looked into how that works, whether it's gzip or something else.

Also, you can use the CLI to browse the message file to get a sense what is in there:
```bash
$ oxmsg dump message.msg

------------------
Message Properties
------------------

header-properties
-----------------
recipient_count:    1

distinguished-properties
------------------------
attachment_count:         0
internet_code_page:       utf-8
message_class:            IPM.Note
sender:                   from@domain.com
...

other properties
-----------------------------------------+---------------+--------------------
property-id                              | type          | value
-----------------------------------------+---------------+--------------------
0x0017 - PidTagImportance                | PtypInteger32 | 00 00 00 01
0x001A - PidTagMessageClass              | PtypString8   | 'IPM.Note'
0x0036 - PidTagSensitivity               | PtypInteger32 | 00 00 00 00
0x0037 - PidTagSubject                   | PtypString8   | 'A test message'
0x003B - PidTagSentRepresentingSearchKey | PtypBinary    | 21 bytes
0x003D - PidTagSubjectPrefix             | PtypString8   | ''
0x0042 - PidTagSentRepresentingName      | PtypString8   | 'from@domain.com'
...
```
